server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      database: xc_cms
      uri:  mongodb://192.168.40.129:27017/xc_cms
    rabbitmq:
      host: 192.168.40.129
      port: 5672
      username: admin
      password: admin
      virtual-host: /
  freemarker:
    cache: false
    settins:
      template_update_delay: 0
