server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
      url: jdbc:mysql://192.168.40.129:33306/xc_course?characterEncoding=utf-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/xuecheng/manage_course/dao/*Mapper.xml
  type-aliases-package: com.xuecheng.framework.domain
# 打印sql
logging:
  level:
     com.xuecheng.manage_course.dao : debug
pagehelper:
  helper-dialect: mysql